
### GET ALL

GET http://localhost:5232/games

### FIND

GET http://localhost:5232/games/4

### CREATE
POST http://localhost:5232/games
Content-Type: application/json

{
    "name": "Need for speed Heat",
    "genreId": 4,
    "price": 19.99,
    "releaseDate": "2019-11-01"
}


### UPDATE

PUT http://localhost:5232/games/4
Content-Type: application/json

{
    "name": "Horizon Zero Dawn",
    "genreId": 6,
    "price": 9.99,
    "releaseDate": "2017-02-17"
}


###DELETE

DELETE http://localhost:5232/games/4